### ISSUE TITLE
Proper cache support

### ISSUE THREAD

**Issue by pablojimpas** [mossymossmoss/menu-searx#2]
Great script!
I've been thinking about integrating something like this to my regular workflow for a while now.
I though that it may be a great improvement to take advantage of a proper caching mechanism to avoid bandwidth usage when possible and retrieve results faster at a cost of (minimal) storage space.

The basic idea is to store results in "$cachedir/$query.json" insted of "$cachedir/results.json" and then before making the curl request checking if we already have the results.
There could be also some sort of mechanism to remove outdated results (e.g. more than x days) and maybe something more advanced like limiting the total disk space usage desired or choosing to keep only the most recent or frequent searches

**Comment by MossyMossMoss** [comment]
Just implemented the feature, very good idea! In it's current form, you can set the maximum number of searches to cache and if you make a search that would surpass the limit set, it will delete the oldest file
